CMPUT301W23T12/6ixStacks

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/qrrush/ProfileAdapter.java
app/src/main/java/com/example/qrrush/ProfileFragment.java
app/src/main/java/com/example/qrrush/QRCode.java
app/src/main/java/com/example/qrrush/QRCodeAdapter.java
app/src/main/java/com/example/qrrush/QRcode.java
app/src/main/java/com/example/qrrush/User.java
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/layout/profile_content.xml

I finished the profile page UI it used hard coded data and some copywrite images for the time being.

41 profile page UI

---

app/build.gradle
app/src/main/java/com/example/qrrush/FirebaseWrapper.java
app/src/main/java/com/example/qrrush/MainActivity.java
build.gradle

This is a Firebase Wrapper API as well as Firebase integration.
Documentation is available here:
https://github.com/CMPUT301W23T12/6ixStacks/wiki/FirebaseWrapper-API-Documentation

Issue 37 Firebase Wrapper

---

app/src/main/java/com/example/qrrush/ProfileFragment.java
app/src/main/java/com/example/qrrush/User.java

This should probably also be done for rank, since you can't just set the rank of a user. Once the leaderboard is on firebase and everything we should replace `getRank` with something which does a firebase call or something.

fixed User class so that score is calculated from the user's QR codes

---

app/src/main/java/com/example/qrrush/MainActivity.java
app/src/main/java/com/example/qrrush/MainFragment.java
app/src/main/java/com/example/qrrush/ProfileFragment.java
app/src/main/java/com/example/qrrush/QRCodeAdapter.java
app/src/main/java/com/example/qrrush/User.java
app/src/main/res/layout/fragment_main.xml

Issue is finished, I also added comments and cleaned up some of the code

21 qr code sum

---

app/src/main/java/com/example/qrrush/CameraFragment.java
app/src/main/java/com/example/qrrush/LeaderboardFragment.java
app/src/main/java/com/example/qrrush/MainActivity.java
app/src/main/java/com/example/qrrush/ShopFragment.java
app/src/main/java/com/example/qrrush/SocialFragment.java

57 adding user object

---

app/src/main/java/com/example/qrrush/ProfileFragment.java
app/src/main/java/com/example/qrrush/QRCode.java
app/src/main/java/com/example/qrrush/QRCodeAdapter.java

You can run the code and go to the profile view to see the visualizations.

visual representation for QR codes

---

app/src/main/java/com/example/qrrush/MainActivity.java
app/src/main/java/com/example/qrrush/ProfileFragment.java

Had duplicate code in the profile fragment.

Bug was fixed

---

app/src/main/java/com/example/qrrush/QRCode.java

Mostly little things like removing an unused variable and using better functions to do a few things.

small fixes in QRCode getImage

---

app/src/main/java/com/example/qrrush/QRCode.java
app/src/main/java/com/example/qrrush/ShopFragment.java

Renamed `QRCode.getNames()` to `QRCode.getName()` and removed the old obselete `QRCode.getName()`, added documentation comments to `QRCode.java`, and made the Profile page display the newly generated QR code names.

Qrcode class refactor

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/qrrush/Geo.java
app/src/main/java/com/example/qrrush/MainActivity.java

This PR adds a function `Geo.getCurrentLocation()` which you pass a callback which will be given the current location once its found.

Added Geolocation API

---

app/src/main/java/com/example/qrrush/MainActivity.java
app/src/main/java/com/example/qrrush/QRCode.java
app/src/main/java/com/example/qrrush/QRCodeAdapter.java
app/src/main/java/com/example/qrrush/ShopFragment.java
app/src/main/res/layout/fragment_shop.xml

The purchased QR codes are also now added to the user's account on firebase.

Display QR Code image in shop, and make shop add codes to user's account

---

app/src/main/java/com/example/qrrush/ProfileFragment.java

I just added labels to the values on the profile page so I know what the numbers are when I test it.

added labels to the stats displayed on the profile page

---

app/src/main/java/com/example/qrrush/QRCode.java
app/src/main/java/com/example/qrrush/QRCodeAdapter.java
app/src/main/java/com/example/qrrush/User.java

QR code objects now have a data field of when they where found or created

Added date field to QR code

---

app/src/main/res/drawable/mtrl_checkbox_button_icon_indeterminate_unchecked1.xml

Bug was fixed unsure why it was not working :/

---

app/src/main/java/com/example/qrrush/Geo.java
app/src/main/java/com/example/qrrush/MainActivity.java
app/src/main/java/com/example/qrrush/MainFragment.java

Location is now done, after asking around and for the Android Emulator you can't emulate your live location, so the only way we can test the location is if you go to settings and emulate your own location when u select a location
However, it works on android devicesso for testing we will use android devices

96 incorrect location

---

app/src/main/java/com/example/qrrush/ProfileFragment.java
app/src/main/java/com/example/qrrush/User.java
app/src/main/res/layout/fragment_profile.xml

Contact: display on User profile will only display if the phone number was entered, if it wasn't the display for contact: won't be there

Contact display

---

app/src/main/java/com/example/qrrush/view/ProfileFragment.java
app/src/main/java/com/example/qrrush/view/QRConfirmFragment.java
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values/themes.xml

The profile page UI looks good on both the Pixel 2 and 3

removed top bar, made app full screen, and fixed profile page UI

---

app/src/main/java/com/example/qrrush/model/FirebaseWrapper.java
app/src/main/java/com/example/qrrush/model/QRCodeAdapter.java
app/src/main/java/com/example/qrrush/model/User.java
app/src/main/java/com/example/qrrush/view/MainActivity.java
app/src/main/java/com/example/qrrush/view/ProfileFragment.java
app/src/main/java/com/example/qrrush/view/SocialFragment.java
app/src/main/res/layout/fragment_social.xml

Added the ability to click on users profiles and view their rank, score, qr codes found, profile img and see a list of their qr codes scanned with location.

26 clicking profiles

---

app/src/main/java/com/example/qrrush/model/FirebaseWrapper.java
app/src/main/java/com/example/qrrush/model/QRCodeAdapter.java
app/src/main/java/com/example/qrrush/view/SocialFragment.java
app/src/main/res/layout/profile_content.xml

Added the ability to view users who have scanned the same QR code, and if you click on their name you will be taken to their profile. :)

22 similar qr codes

---

app/src/main/java/com/example/qrrush/view/MainFragment.java

If a user scans a QR code, it will now put it on the map (if geolocation accepted) thanks to @VelocityEX . Now when u click a marker it will show you who scanned it and you can click on their profile and view their profile.

6 clickable markers

---

app/src/main/java/com/example/qrrush/view/MainActivity.java
app/src/main/java/com/example/qrrush/view/MainFragment.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_main.xml

Currently the loading screen is just a TextView that says `Loading...`, but this can be changed. What's important is that it works.

Added loading screen to app

---

app/src/main/java/com/example/qrrush/model/FirebaseWrapper.java
app/src/main/java/com/example/qrrush/model/User.java
app/src/main/java/com/example/qrrush/view/LoginActivity.java
app/src/main/java/com/example/qrrush/view/ProfileFragment.java
app/src/main/java/com/example/qrrush/view/ShopFragment.java
app/src/main/res/layout/fragment_profile.xml

Add in game currency

---

app/src/androidTest/java/com/example/qrrush/ProfileTest.java
app/src/androidTest/java/com/example/qrrush/SearchTest.java
app/src/main/java/com/example/qrrush/model/SearchPlayerAdapter.java
app/src/main/java/com/example/qrrush/model/User.java
app/src/main/java/com/example/qrrush/view/LoginActivity.java
app/src/main/java/com/example/qrrush/view/ProfileDialogFragment.java
app/src/main/java/com/example/qrrush/view/ProfileFragment.java
app/src/main/java/com/example/qrrush/view/SocialFragment.java
app/src/main/res/layout/fragment_social.xml
app/src/main/res/layout/searchedplayers_content.xml

Fully works but when swiping off the fragment the searched users still stay there, should clear it.

Other players profiles show up while searching along with there images

---

app/src/main/java/com/example/qrrush/model/FirebaseWrapper.java
app/src/main/java/com/example/qrrush/model/LeaderboardQRCodeAdapter.java
app/src/main/java/com/example/qrrush/model/QRCode.java
app/src/main/java/com/example/qrrush/model/QRCodeAdapter.java
app/src/main/java/com/example/qrrush/model/User.java
app/src/main/java/com/example/qrrush/view/LeaderboardFragment.java
app/src/main/java/com/example/qrrush/view/LoginActivity.java
app/src/main/java/com/example/qrrush/view/QRConfirmFragment.java
app/src/main/res/layout/fragment_qr_confirm.xml
app/src/main/res/layout/profile_content.xml

Qrcode location images

---

app/src/main/java/com/example/qrrush/view/ProfileFragment.java
app/src/main/res/drawable/rounded_dialog_background.xml
app/src/main/res/layout/profile_overlay.xml
app/src/main/res/values/settings.xml

I changed the UI of the alertDialog for editName

gave color to the editName alertDialog
